# -*- coding: utf-8 -*-

animeportal_plot = {
    'anidub':'Ресурс, на котором контент создаётся, а не "заимствуется". Мы работаем, чтобы вы отдыхали. ©',
    'anilibria':'Заходите и оставайтесь! Улыбнитесь, ведь вы нашли то место, где вам будет хорошо. ©',
    'animedia':'Наш проект занимается озвучиванием и адаптацией иностранной мультипликации на русский язык... ©',
    'anistar':'Наши переводы самые быстрые и качественные в Рунете! У нас приятная и привычная многим озвучка... ©',
    'shizaproject': 'Мы — безумный коллектив, занимающийся адаптацией зарубежной анимации для русскоязычной публики... ©'
    }

animeportal_data = '[play]\n\
[COLOR blue]Торрент просмотр:[/COLOR]\n\
- В настройках плагина зайти в раздел [COLOR blue]P2P[/COLOR], выбрать торрент движок или торрент Менеджер [COLOR gold]TAM[/COLOR] - выставив предпочитаемый движок\n\
- Просмотр зависит от наличия людей на раздаче искомого торрента файла\n\
- Вся необходимая информация по загрузке и установке Движков находится на форуме [COLOR gold]xbmc.ru[/COLOR]\n\
[COLOR gray]=====================================================[/COLOR]\n\
[COLOR blue]Онлайн просмотр:[/COLOR]\n\
- Использует [COLOR gold]KODI[/COLOR] проигрыватель. Дополнительные настройки не требуются\n\
- Просмотр зависит от скорости вашего интернета, нагрузки на сайт и общей нагрузки на сеть интернет\n\
[/play]\n\
[news]\n\
[B][COLOR=darkorange]Version 0.4.3[/COLOR][/B]\n\
    - Унификация кода под версии Kodi-18, Kodi-19\n\
[COLOR gray]=====================================================[/COLOR]\n\
[/news]\n\
[bugs]\n\
[COLOR blue]Список ошибок не полный и будет постепенно дополняться.[/COLOR]\n\
[COLOR gray]=====================================================[/COLOR]\n\
[B][COLOR red]ERROR: 100[/COLOR][/B]\n\
Ошибка при попытке скачать Базу Данных Аниме с репозитория\n\
Ошибка не критична. Плагин создаст новую и начнет заполнять ее с нуля, но с готовой БД быстрее и удобнее\n\
Рекомендуется сообщить об ошибке автору плагина\n\
[COLOR gray]=====================================================[/COLOR]\n\
[B][COLOR red]ERROR: 101[/COLOR][/B]\n\
Ошибка в парсере, при попытке добавить аниме в Базу Данных\n\
Рекомендуется сообщить автору плагина ID аниме (не обязательно целиком)\n\
[COLOR gray]=====================================================[/COLOR]\n\
[B][COLOR red]ERROR: 102[/COLOR][/B]\n\
Ошибка в модуле очистки Истории Поиска\n\
Рекомендуется сообщить автору плагина название аниме\n\
[COLOR gray]=========================================================================[/COLOR]\n\
[B][COLOR red]ERROR: 103[/COLOR][/B]\n\
Ошибка в модуле обработки Избранного\n\
Рекомендуется сообщить автору плагина название аниме\n\
[COLOR gray]=========================================================================[/COLOR]\n\
[B][COLOR red]ERROR: 404[/COLOR][/B]\n\
Типичная ошибка - Страница не найдена, удалена, перемещена\n\
Рекомендуется зайти на сайт и проверить страницу\n\
[COLOR gray]=========================================================================[/COLOR]\n\
[B][COLOR red]ERROR: 403[/COLOR][/B]\n\
Типичная ошибка - Доступ запрещен, вам отказано в доступе к этой странице\n\
Рекомендуется зайти на сайт и узнать причину ограничения доступа\n\
[/bugs]'
#========================#========================#========================#========================#========================#
anistar_categories=[
    ('thriller/','Боевик'),
    ('vampires/','Вампиры'),
    ('ani-garem/','Гарем'),
    ('detective/','Детектив'),
    ('drama/','Драма'),
    ('history/','История'),
    ('cyberpunk/','Киберпанк'),
    ('comedy/','Комедия'),
    ('maho-shoujo/','Махо-седзе'),
    ('fur/','Меха'),
    ('parodies/','Пародии'),
    ('senen/','Сёнен'),
    ('sports/','Спорт'),
    ('mysticism/','Мистика'),
    ('music/','Музыкальное'),
    ('everyday-life/','Повседневность'),
    ('adventures/','Приключения'),
    ('romance/','Романтика'),
    ('shoujo/','Сёдзе'),
    ('senen-ay/','Сёнен-ай'),
    ('horror/','Триллер'),
    ('horor/','Ужасы'),
    ('fantasy/','Фантастика'),
    ('fentezi/','Фэнтези'),
    ('school/','Школа'),
    ('echchi-erotic/','Эччи'),
    ('action/','Экшен'),
    ('metty/','Этти'),
    ('seinen/','Сейнен'),
    ('demons/','Демоны'),
    ('magic/','Магия'),
    ('super-power/','Супер сила'),
    ('military/','Военное'),
    ('kids/','Детское'),
    ('supernatural/','Сверхъестественное'),
    ('psychological/','Психологическое'),
    ('historical/','Исторический'),
    ('samurai/','Самураи'),
    ('martial-arts/','Боевые искусства'),
    ('police/','Полиция'),
    ('space/','Космос'),
    ('game/','Игры'),
    ('josei/','Дзёсэй'),
    ('shoujo-ai/','Сёдзе Ай')
    ]

anistar_years = [
    '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
    '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000',
    '1999', '1998', '1997', '1996', '1995', '1994', '1993', '1992', '1991', '1990', '1989',
    '1988', '1987', '1986', '1985', '1984', '1983', '1982', '1981', '1980', '1979', '1978',
    '1976', '1975', '1972', '1969', '1968']

anistar_ignor_list = ['7013','6930','6917','6974','6974','4106','1704','1229','1207','1939','1954',
              '2282','4263','4284','4288','4352','4362','4422','4931','5129','5130','5154',
              '5155','6917','6928','6930','6932','6936','6968','6994','7013','7055','3999',
              '4270','4282','4296','4300','4314','4348','4349','4364','4365','4366','4367',
              '4368','4369','4374','4377','4480','4493','4556','6036','3218','3943','3974',
              '4000','4091']

#========================#========================#========================#========================#========================#
shiza_year = (
    '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', 
    '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', 
    '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', 
    '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', 
    '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021')

shiza_season = {
    '':'',
    'Весна':'SPRING',
    'Лето':'SUMMER',
    'Осень':'FALL',
    'Зима':'WINTER'
    }

shiza_categories = {
    '':'',
    'Аниме':'Q2F0ZWdvcnk6NDU4OTE0MTQ4Njg4ODU1MzE=',
    'Дорамы':'Q2F0ZWdvcnk6NDU4OTE0MTQ4Njg4ODU1MzI=',
    'Мультфильмы':'Q2F0ZWdvcnk6NDU4OTE0MTQ4Njg4ODU1MzM=',
    'Разное':'Q2F0ZWdvcnk6NDU4OTE0MTQ4Njg4ODU1MzQ='
    }

shiza_status = {
    '':'',
    'Анонс':'ANNOUNCE',
    'Онгоинг':'ONGOING',
    'Выпущено':'RELEASED',
    'Приостановлено':'SUSPENDED'
    }

shiza_voice_stat = {
    '':'',
    'Хочучка':'WISH',
    'Заморожено':'FROZEN',
    'В работе':'WORK_IN_PROGRESS',
    'Звершено':'COMPLETED',
    'Брошено':'DROPPED'
    }

shiza_form = {
    '':'',
    'ТВ':'TV',
    'ТВ-спешл':'TV_SPECIAL',
    'Остальное':'OTHER',
    'Фильм':'MOVIE',
    'Короткий Фильм':'SHORT_MOVIE',
    'OVA':'OVA',
    'ONA':'ONA',
    'Музыкальный':'MUSIC'
    }

shiza_rating = ('','G','PG','PG_13','R','R_PLUS','RX')

shiza_genre = {
    '':'',
    'экшен':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzM=',
    'комедия':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzQ=',
    'романтика':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODc=',
    'фэнтези':'R2VucmU6NDU4OTE0MjEzMzIzMDc5Nzk=',
    'фантастика':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDE=',
    'драма':'R2VucmU6NDU4OTE0MjEzMzIzMDc5Njg=',
    'школа':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODg=',
    'сверхъестественное':'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTk=',
    'сёнен':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODk=',
    'приключения':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzE=',
    'повседневность':'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTY=',
    'сейнен':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMTA=',
    'детектив':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDU=',
    'этти':'R2VucmU6NDU4OTE0MjEzMzIzMDc5Nzg=',
    'магия':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODM=',
    'меха':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODQ=',
    'гарем':'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTQ=',
    'военное':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDQ=',
    'космос':'R2VucmU6NDU4OTE0MjEzMzIzMDc5Nzc=',
    'триллер':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDA=',
    'игры':'R2VucmU6NDU4OTE0MjEzMzIzMDc5Njk=',
    'музыка':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzI=',
    'супер сила':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDM=',
    'психологическое':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzA=',
    'демоны':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzU=',
    'ужасы':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODI=',
    'сёдзё':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDI=',
    'исторический':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODE=',
    'спорт':'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTA=',
    'вампиры':'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTE=',
    'пародия':'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODU=',
    'боевые искусства':'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDg=',
    'полиция':'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzY='
    }

shiza_direction = {
    'По убыванию':'DESC',
    'По возрастанию':'ASC'
    }

shiza_sort = {
    'Дате публикации':'PUBLISHED_AT',
    'Дате обновление':'UPDATED_AT',
    'Просмотрам':'VIEW_COUNT',
    'Названию EN':'ORIGINAL_NAME',
    'Названию RU':'NAME',
    'Рейтингу':'SCORE'
    }

shiza_tags = {
    '':'',
    'Дружба':'VGFnOjQ1ODkxNDE0ODg1NjYyNzI0',
    'Повседневность':'VGFnOjQ1ODkxNDE0ODg1NjYyODA3',
    'Кровь':'VGFnOjQ1ODkxNDE0ODg1NjYyODk2',
    'Будущее':'VGFnOjQ1ODkxNDE0ODg5ODU3MDI5',
    'bdrip':'VGFnOjQ1ODkxNDE0ODgxNDY4NDE4',
    'webrip':'VGFnOjQ1ODkxNDE0ODg1NjYyODAw',
    'Школа':'VGFnOjQ1ODkxNDE0ODg1NjYyNzM2',
    'Олдскул':'VGFnOjQ1ODkxNDE0ODg1NjYyNzY1',
    'Магия':'VGFnOjQ1ODkxNDE0ODg1NjYyNzk5',
    'hdtvrip':'VGFnOjQ1ODkxNDE0ODg5ODU3MDM0',
    'Демоны':'VGFnOjQ1ODkxNDE0ODg1NjYyNzQ5',
    'Война':'VGFnOjQ1ODkxNDE0ODg1NjYyODAy',
    'Роботы':'VGFnOjQ1ODkxNDE0ODg1NjYyNzcz',
    'Космос':'VGFnOjQ1ODkxNDE0ODg1NjYyNzI4',
    'Любовь':'VGFnOjQ1ODkxNDE0ODg1NjYyODU0',
    'Вампиры':'VGFnOjQ1ODkxNDE0ODg1NjYyNzMy',
    'Оружие':'VGFnOjQ1ODkxNDE0ODg1NjYyNzMz'
    }

shiza_genres2 = {
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzM=': 'экшен',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzQ=': 'комедия',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODc=': 'романтика',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5Nzk=': 'фэнтези',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDE=': 'фантастика',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5Njg=': 'драма',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODg=': 'школа',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTk=': 'сверхъестественное',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODk=': 'сёнен',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzE=': 'приключения',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTY=': 'повседневность',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMTA=': 'сейнен',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDU=': 'детектив',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5Nzg=': 'этти',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODM=': 'магия',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODQ=': 'меха',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTQ=': 'гарем',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDQ=': 'военное',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5Nzc=': 'космос',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDA=': 'триллер',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5Njk=': 'игры',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzI=': 'музыка',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDM=': 'супер сила',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzA=': 'психологическое',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzU=': 'демоны',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODI=': 'ужасы',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDI=': 'сёдзё',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODE=': 'исторический',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTA=': 'спорт',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5OTE=': 'вампиры',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5ODU=': 'пародия',
    'R2VucmU6NDU4OTE0MjEzMzIzMDgwMDg=': 'боевые искусства',
    'R2VucmU6NDU4OTE0MjEzMzIzMDc5NzY=': 'полиция'
    }

studios = {
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczNzk5': 'A-1 Pictures',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzQ5': 'Bridge',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMzEx': 'Bakken Record',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjk1': 'J.C.Staff',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTYw': 'Revoroot',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjE3': 'Doga Kobo',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ0': 'MAPPA',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTE4': 'Nomad',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTU5': 'Millepensee',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTQx': "Brain's Base",
    'U3R1ZGlvOjQ1ODkxNDIxMzMyMzA4MDE0': 'Bones',
    'U3R1ZGlvOjQ1ODkxNDIxMzc0MjUxMDEw': 'Telecom Animation Film',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjQx': 'Asread',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMzA1': 'Okuruto Noboru',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODAz': 'SILVER LINK.',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk1': 'Studio Deen',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjcz': 'Toei',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTQ4': '8bit',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTU2': 'C-Station',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODcx': 'Platinum Vision',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjky': 'Team TillDawn',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTQ3': 'Orange',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjc4': 'Bibury Animation',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTMw': 'White Fox',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2Njcy': 'TMS',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjk4': 'Production I.G',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjky': 'TNK',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDg5': 'Science SARU',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzcw': 'Geno',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzMw': 'Hoods',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODUz': 'Colorido',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDIw': 'David',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTIz': 'feel.',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTI0': 'P.A. Works',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTA0': 'Seven Arcs',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDU2': 'Zero-G',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDE0': 'Lerche',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTE4': 'Gokumi',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMzAx': 'Hokiboshi',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5NzU5': 'Bandai Namco Pictures',
    'U3R1ZGlvOjQ2MjUxNDcwNTc5ODI2Njg4': 'Studio Comet',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjc2': 'Marvy Jack',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5NzY0': 'CloverWorks',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQz': 'Tezuka',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTU4': 'Kyoto',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTYx': 'Tear',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTY4': 'Imagineer',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzI1': 'Shaft',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjg5': 'Arvo',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzA3': 'Shin-Ei',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTM2': 'Pine Jam',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzI1': 'Project No.9',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjAy': 'Ajia-Do',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjM5': 'TROYCA',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MTkw': 'Magic Bus',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTY5': 'PuYUKAI',
    'U3R1ZGlvOjQ1ODkxNDIxMzc0MjUxMDQz': 'Trigger',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTY4': 'Imagineer',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjg0': 'DMM.futureworks',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg0': 'Satelight',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjc1': 'HORNETS',
    'U3R1ZGlvOjQ1ODkxNDIxNDE2MTk0MDU0': 'Ezόla',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODQ3': 'Nexus',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjA5': 'CoMix Wave Films',
    'U3R1ZGlvOjQ1ODkxNDIxMzMyMzA4MDE2': 'Pierrot',
    'U3R1ZGlvOjQ1ODkxNDIxNDE2MTk0MDQ4': 'Lapin Track',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzQ2': 'Wit',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTM5': 'EMT Squared',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ2': 'LandQ',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MTk5': 'ufotable',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDQx': 'Kinema Citrus',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTk5': 'Yokohama Animation Lab',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzAx': 'Madhouse',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTMw': 'White Fox',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzQ1': 'Seven Arcs Pictures',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5NzY0': 'CloverWorks',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjgx': 'DRAWIZ',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjE3': 'Encourage Films',
    'U3R1ZGlvOjQ4MjEyMjg3MDM4Njg1MTg0': 'Platinumvision',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjI5': 'A.C.G.T.',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTYy': 'Lay-duce',
    'U3R1ZGlvOjQ1ODkxNDIxNDMyOTcxMjcx': 'Maho Film',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTEx': 'AIC Build',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ0': 'MAPPA',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjQ5': '3Hz',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTUz': 'Diomedéa',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjQ0': 'Connect',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzk4': 'Sola Digital Arts',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTQ0': 'Pierrot Plus',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2Njc4': 'Xebec',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDQ5': 'Seven',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTYx': 'Tear',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTYy': 'Lay-duce',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzc5': 'production doA',
    'U3R1ZGlvOjQ1ODkxNDIxNDI4Nzc2OTYz': 'Stingray',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTQy': 'NAZ',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjYw': 'Passione',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzAx': 'Madhouse',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTc5': 'Production GoodBook',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzkz': 'Gaina',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5NzY0': 'CloverWorks',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDU2': 'Zero-G',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5ODAx': 'Lings',
    'U3R1ZGlvOjQ4MTgxNjI4NDkyNTc4ODE2': 'Yamato Works',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjQ0': 'Connect',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTc5': 'Chizu',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODgz': 'M.S.C',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTU2': 'B.CMAY PICTURES',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjE1': 'Gonzo',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTUx': 'Creators in Pack',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzg3': 'The Answer',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODQ3': 'Nexus',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzI2': 'Blanc',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg1': 'Graphinica',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTc4': 'Signal.MD',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzg3': 'The Answer',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzA3': 'Shin-Ei',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczNzk5': 'A-1 Pictures',
    'U3R1ZGlvOjQ2MTQ2NTM0Mjc3OTA2NDMy': 'Hal Film Maker',
    'U3R1ZGlvOjQ1ODkxNDIxMzMyMzA4MDEx': 'Sunrise',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ0': 'Production Reed',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjQ5': '3Hz',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDcz': 'Haoliners Animation League',
    'U3R1ZGlvOjQ1ODkxNDIxNDExOTk5Nzgy': 'CygamesPictures',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTA1': 'Hibari',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTU5': 'Millepensee',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTY0': 'Nut',
    'U3R1ZGlvOjQ1ODkxNDIxMzc0MjUxMDE2': 'TYO Animations',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTc4': 'Signal.MD',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzUy': 'Production IMS',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTYw': 'GEMBA',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTUy': 'C2C',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDcx': 'A-Real',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjQ3': 'Shuka',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg1': 'Graphinica',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDQ0': 'AXsiZ',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzA3': 'Fantasia',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDUy': 'M2',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTQx': 'Sega',
    'U3R1ZGlvOjQ1ODkxNDIxNDA3ODA1NDY2': 'Typhoon Graphics',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg1': 'Graphinica',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg1': 'Graphinica',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODIx': 'Manglobe',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg1': 'Graphinica',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODU1': 'Actas',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDQ1': 'SANZIGEN',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NDk0': 'Khara',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5Njc0': 'Polygon Pictures',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODc2': 'Hoods Drifters',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTk3': 'Namu',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODQ5': 'GoHands',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjQ5': 'Do',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODMy': 'Ordet',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTM5': 'EMT Squared',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODcx': 'Platinum Vision',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjg5': 'AIC',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxNDAzNjExMTYw': 'GEMBA',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NDg4': 'Zexcs',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTQ3': 'Orange',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTI4': 'Arms',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjIx': 'Tatsunoko',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjA4': 'Gainax',
    'U3R1ZGlvOjQ1ODkxNDIxMzk1MjIyNTQ5': 'Moriken',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODM5': 'VOLN',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzQ2': 'Wit',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2Njgx': 'Daume',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjQ5': '3Hz',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDQ1': 'SANZIGEN',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjQ0': 'Connect',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzEw': 'Comet',
    'U3R1ZGlvOjQ1ODkxNDIxMzk5NDE2ODM5': 'VOLN',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTMw': 'White Fox',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzQ5': 'Bridge',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NDg4': 'Zexcs',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjQx': 'Asread',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTI0': 'LIDENFILMS',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzIy': 'Artland',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjM5': 'TROYCA',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTg1': 'Graphinica',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjU3': 'teamKG',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTA1': 'Hibari',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjE3': 'Encourage Films',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjIz': 'Felix Film',
    'U3R1ZGlvOjQ2MjQ4NDEzMDI4Njc5Njgw': 'Harmony Gold',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODMy': 'Ordet',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk5': 'Artmic',
    'U3R1ZGlvOjQ1ODkxNDIxMzkxMDI4MjM5': 'TROYCA',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTc2': 'OLM',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzU3': 'Ghibli',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1Mzcw': 'I.Gzwei',
    'U3R1ZGlvOjQ4MTkxNjIyNzU5ODQxNzky': 'Studio 4°C',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjEw': '4C',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjg5': 'AIC',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTQ3': 'Orange',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjI3': 'Agent 21',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTI1': 'Primastea',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTMz': 'Kaname',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjQ0': 'Connect',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5Njgx': 'Yaoyorozu',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzI1': 'Project No.9',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjIx': 'Tatsunoko',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTkx': 'Vega',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjYy': 'Group TAC',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjU4': 'Darts',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ2': 'animate Film',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk5': 'Artmic',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTUy': 'C2C',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTcw': 'Toshiba',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjY5': 'Tokyo Movie Shinsha',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjM3': 'WAO World',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2Njg2': 'Idea Factory',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTIw': 'Hakk',
    'U3R1ZGlvOjQ4MTg5Mzg5MTcxMzI2OTc2': 'Nakamura Production',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjcz': 'Toei',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTcz': 'DAX',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk5': 'Artmic',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjU1': 'Media Blasters',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjM5': 'Mushi',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ0': 'MAPPA',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTQ3': 'Oh!',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTMy': 'Remic',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTIz': 'feel.',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjYw': 'D.A.S.T.',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTQx': 'AIC PLUS+',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTIz': 'feel.',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODUy': 'Tama',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTQw': 'Signal',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ0': 'MAPPA',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzM5': 'Rikka',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODMy': 'Ordet',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzM3': 'Junio',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ2': 'animate Film',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjU1': 'Media Blasters',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwODgz': 'March',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTYy': 'Lay-duce',
    'U3R1ZGlvOjQ1ODkxNDIxMzg2ODMzOTMw': 'Opera House',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDM5': 'Lilix',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTM3': 'Nippon',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjA5': 'CoMix Wave Films',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDQx': 'Kinema Citrus',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTIy': 'Gallop',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzE5': 'Ashi',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwODkw': 'Filmlink International',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTE0': 'Aubec',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQw': 'Purple Cow Studio Japan',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDE2': 'MooGoo',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwODk5': 'Triangle Staff',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODQ0': 'AIC ASTA',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzAx': 'Madhouse',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjg5': 'AIC',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczNzk0': 'BeSTACK',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk5': 'Artmic',
    'U3R1ZGlvOjQ1ODkxNDIxMzYxNjY4MTM1': 'AIC Takarazuka',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTQw': 'Nippon Columbia',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjUz': 'Kadokawa Shoten',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTI2': 'Sony Music',
    'U3R1ZGlvOjQ1ODkxNDIxMzgyNjM5NjU2': 'Victor',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjA2': 'Mook',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2Njg2': 'Idea Factory',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTE1': 'Kyuuma',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjAz': 'Bandai Visual',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjMy': 'KSS',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ5': 'Tokyo Kids',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTUw': 'SME Visual Works',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NDg4': 'Zexcs',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjg5': 'AIC',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk5': 'Artmic',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjM4': 'Hiro Media',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ2': 'animate Film',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTAz': 'Phoenix',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ2': 'animate Film',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NTk5': 'Artmic',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ5': 'PrimeTime',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjg5': 'AIC',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTQ4': '8bit',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTQ4': '8bit',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDI4': 'Bandai',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjMy': 'Think Corporation',
    'U3R1ZGlvOjQ1ODkxNDIxMzU3NDczODQw': 'Bee Train',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTMw': 'Minami Machi Bugyousho',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDE3': 'Jinnis Animation',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTUz': 'Digital Frontier',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjY1': 'Azeta Pictures',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzQ2': 'LandQ',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzM0': 'Radix',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTQ4': '8bit',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzA4': 'Oxybot',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTA5': 'REALTHING',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MjM3': 'Unicorn',
    'U3R1ZGlvOjQ1ODkxNDIxMzQwNjk2NjQ0': 'Production Reed',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NTE1': 'Nikkatsu',
    'U3R1ZGlvOjQ1ODkxNDIxMzc4NDQ1MzI2': 'Blanc',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ5MDg1MTg3': 'Trans Arts',
    'U3R1ZGlvOjQ1ODkxNDIxMzY1ODYyNDQ1': 'SANZIGEN',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMzM1': 'Marine',
    'U3R1ZGlvOjQ1ODkxNDIxMzUzMjc5NDg4': 'Zexcs',
    'U3R1ZGlvOjQ1ODkxNDIxMzM2NTAyMjcz': 'Toei',
    'U3R1ZGlvOjQ1ODkxNDIxMzQ0ODkwOTI4': 'Soeishinsha',
    'U3R1ZGlvOjQ1ODkxNDIxMzcwMDU2NzUy': 'Production IMS'
    }